package m.l.cook;

import java.awt.Color;
import java.awt.Font;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;


public class JedalnicekJPanel extends javax.swing.JPanel {

    private JedalnicekTableModel jedalnicekTableModel;
    private JedalnicekReceptyComboBoxModel receptyComboBoxModel;
    private JedalnicekDatumComboBoxModel datumComboBoxModel;

    private JedalnicekDao jedalnicekDao = ObjectFactory.INSTANCE.jedalnicekDao();

    /**
     * Creates new form JedalnicekJPanel
     */
    public JedalnicekJPanel() {
        jedalnicekTableModel = new JedalnicekTableModel();
        receptyComboBoxModel = new JedalnicekReceptyComboBoxModel();
        datumComboBoxModel = new JedalnicekDatumComboBoxModel();
        initComponents();
        setBackground(new Color(149, 189, 110));
        jedalnicekDao.vymazAkJePo();
        jedalnicekTable.getTableHeader().setFont(new Font("Caviar Dreams", Font.BOLD, 14));
        jedalnicekTable.setAutoCreateRowSorter(true);
    }

    private void aktualizovatJedalnicek() {

        JedalnicekTableModel model = (JedalnicekTableModel) jedalnicekTable.getModel();

        model.aktualizovat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jedalnicekJLabel = new javax.swing.JLabel();
        datumComboBox = new javax.swing.JComboBox<>();
        receptComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jedalnicekTable = new javax.swing.JTable();
        datumJLabel = new javax.swing.JLabel();
        receptJLabel = new javax.swing.JLabel();
        pridajButton = new javax.swing.JButton();

        setBounds(new java.awt.Rectangle(0, 0, 620, 530));
        setPreferredSize(new java.awt.Dimension(620, 530));

        jedalnicekJLabel.setFont(new java.awt.Font("Caviar Dreams", 1, 36)); // NOI18N
        jedalnicekJLabel.setText("Jedálniček");
        jedalnicekJLabel.setMaximumSize(new java.awt.Dimension(295, 47));
        jedalnicekJLabel.setMinimumSize(new java.awt.Dimension(295, 47));
        jedalnicekJLabel.setPreferredSize(new java.awt.Dimension(295, 47));

        datumComboBox.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        datumComboBox.setModel(datumComboBoxModel);

        receptComboBox.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        receptComboBox.setModel(receptyComboBoxModel);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(620, 530));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(620, 530));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(620, 530));

        jedalnicekTable.setFont(new java.awt.Font("Caviar Dreams", 1, 12)); // NOI18N
        jedalnicekTable.setModel(jedalnicekTableModel);
        jedalnicekTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jedalnicekTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jedalnicekTable);

        datumJLabel.setFont(new java.awt.Font("Caviar Dreams", 1, 15)); // NOI18N
        datumJLabel.setText("Dátum:");

        receptJLabel.setFont(new java.awt.Font("Caviar Dreams", 1, 15)); // NOI18N
        receptJLabel.setText("Recept:");

        pridajButton.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        pridajButton.setText("Pridaj");
        pridajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jedalnicekJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(datumJLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(receptJLabel))
                                    .addComponent(receptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pridajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jedalnicekJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datumJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pridajButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(datumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(receptJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pridajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajButtonActionPerformed
        Jedalnicek jedalnicek = new Jedalnicek();
        DateTimeFormatter formatter = DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM);

        jedalnicek.setDatum((LocalDate.parse((String) datumComboBox.getSelectedItem(), formatter)).plusDays(1));
        jedalnicek.setRecept((Recept) receptComboBox.getSelectedItem());

        jedalnicekDao.saveOrUpdate(jedalnicek);

        aktualizovatJedalnicek();
    }//GEN-LAST:event_pridajButtonActionPerformed

    private void jedalnicekTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jedalnicekTableMouseClicked
        JTable jt = (JTable) evt.getSource();

        if (evt.getClickCount() == 2) {

            int selectedRow = jedalnicekTable.getSelectedRow();
            int convertRowIndexToModel = jedalnicekTable.convertRowIndexToModel(selectedRow);
            Jedalnicek zvolenyJedalnicek = jedalnicekTableModel.getObjectAt(convertRowIndexToModel);
            List<Jedalnicek> dajJedalnicek = jedalnicekDao.dajJedalnicek();
            for (Jedalnicek jedalnicek : dajJedalnicek) {
                if (jedalnicek.getId().equals(zvolenyJedalnicek.getId())) {
                    zvolenyJedalnicek = jedalnicek;
                }
            }
            JedalnicekUpravaJDialog upravaJedalnickaJDialog = new JedalnicekUpravaJDialog(zvolenyJedalnicek, (JFrame) this.getRootPane().getParent());
            upravaJedalnickaJDialog.setVisible(true);

            aktualizovatJedalnicek();
        }
    }//GEN-LAST:event_jedalnicekTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> datumComboBox;
    private javax.swing.JLabel datumJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jedalnicekJLabel;
    private javax.swing.JTable jedalnicekTable;
    private javax.swing.JButton pridajButton;
    private javax.swing.JComboBox<Recept> receptComboBox;
    private javax.swing.JLabel receptJLabel;
    // End of variables declaration//GEN-END:variables
}
