/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m.l.cook;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JTable;

/**
 *
 * @author martinapivarnikova
 */
public class NakupnyZoznamJPanel extends javax.swing.JPanel {

    private NakupnyZoznamTableModel nakupnyZoznamTableModel;
    private NakupnyZoznamIngrediencieComboBoxModel nakupnyZoznamComboBoxModel;
    private NakupnyZoznamDao nakupnyZoznamDao = ObjectFactory.INSTANCE.nakupnyZoznamDao();
    
    Frame parent;
    NakupnyZoznamDonaskaJDialog pizzaJDialog;

    /**
     * Creates new form NakupnyZoznamJPanel
     */
    public NakupnyZoznamJPanel() {
        nakupnyZoznamTableModel = new NakupnyZoznamTableModel();
        nakupnyZoznamComboBoxModel = new NakupnyZoznamIngrediencieComboBoxModel();

        initComponents();
        setBackground(new Color(149, 189, 110));
        nakupnyZoznamTable.setBackground(Color.WHITE);
        
        nakupnyZoznamTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        nakupnyZoznamTable.getColumnModel().getColumn(0).setPreferredWidth(502);
        nakupnyZoznamTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        nakupnyZoznamTable.getTableHeader().setFont(new Font("Caviar Dreams", Font.BOLD, 14));
        

    }

    private void aktualizovatNakupnyZoznam() {

        NakupnyZoznamTableModel model = (NakupnyZoznamTableModel) nakupnyZoznamTable.getModel();
        // aktualizuj ho
        model.aktualizovat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        nakupnyZoznamTable = new javax.swing.JTable();
        ingrediencieComboBox = new javax.swing.JComboBox<>();
        pridajButton = new javax.swing.JButton();
        pridajIngredienciuButton = new javax.swing.JButton();
        nakupnyZoznamJLabel = new javax.swing.JLabel();

        setBounds(new java.awt.Rectangle(0, 0, 620, 530));
        setPreferredSize(new java.awt.Dimension(620, 530));
        setRequestFocusEnabled(false);

        nakupnyZoznamTable.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        nakupnyZoznamTable.setModel(nakupnyZoznamTableModel);
        nakupnyZoznamTable.setSelectionBackground(new java.awt.Color(204, 204, 0));
        nakupnyZoznamTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NakupnyZoznamJPanel.this.mouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(nakupnyZoznamTable);

        ingrediencieComboBox.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        ingrediencieComboBox.setModel(nakupnyZoznamComboBoxModel);
        ingrediencieComboBox.setMinimumSize(new java.awt.Dimension(96, 29));
        ingrediencieComboBox.setPreferredSize(new java.awt.Dimension(96, 29));

        pridajButton.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        pridajButton.setText("Pridaj");
        pridajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajButtonActionPerformed(evt);
            }
        });

        pridajIngredienciuButton.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        pridajIngredienciuButton.setText("Pridaj ingredienciu...");
        pridajIngredienciuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajIngredienciuButtonActionPerformed(evt);
            }
        });

        nakupnyZoznamJLabel.setFont(new java.awt.Font("Caviar Dreams", 1, 36)); // NOI18N
        nakupnyZoznamJLabel.setText("Nákupný zoznam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(ingrediencieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(pridajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pridajIngredienciuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nakupnyZoznamJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nakupnyZoznamJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingrediencieComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pridajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pridajIngredienciuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pridajIngredienciuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajIngredienciuButtonActionPerformed
        NakupnyZoznamPridajIngredienciuJDialog pridajIngredienciuJDialog = new NakupnyZoznamPridajIngredienciuJDialog((JFrame) this.getRootPane().getParent(), true);
        pridajIngredienciuJDialog.setVisible(true);

        ((NakupnyZoznamIngrediencieComboBoxModel) ingrediencieComboBox.getModel()).refresh();

    }//GEN-LAST:event_pridajIngredienciuButtonActionPerformed

    private void pridajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajButtonActionPerformed
        NakupnyZoznam nakupnyZoznam = new NakupnyZoznam();
        nakupnyZoznam.setPolozka((Ingrediencia) ingrediencieComboBox.getSelectedItem());

        nakupnyZoznamDao.pridaj(nakupnyZoznam);

        pizzaJDialog = new NakupnyZoznamDonaskaJDialog(parent, true);
        if (nakupnyZoznamTable.getRowCount() > 10) {
            pizzaJDialog.setVisible(true);
        }
        
        aktualizovatNakupnyZoznam();
    }//GEN-LAST:event_pridajButtonActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        // TODO add your handling code here:private void mouseClicked(MouseEvent e) {
        JTable target = (JTable) evt.getSource();

        if (evt.getClickCount() == 2) {

            int row = nakupnyZoznamTable.getSelectedRow();
            int column = nakupnyZoznamTable.getSelectedColumn();

            if (column == 1) {
                nakupnyZoznamDao.vymaz(nakupnyZoznamTableModel.getObjectAt(row));
                aktualizovatNakupnyZoznam();
            }

        }

    }//GEN-LAST:event_mouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Ingrediencia> ingrediencieComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nakupnyZoznamJLabel;
    private javax.swing.JTable nakupnyZoznamTable;
    private javax.swing.JButton pridajButton;
    private javax.swing.JButton pridajIngredienciuButton;
    // End of variables declaration//GEN-END:variables
}
