package m.l.cook;

import java.awt.Color;
import java.awt.Frame;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import javax.swing.SwingUtilities;

public class PridajReceptJDialog extends javax.swing.JDialog {

    private Recept recept;
    
    private ReceptDao receptDao = ObjectFactory.INSTANCE.receptDao();
    
    ReceptyJpanel receptyJpanel;
    
   
    //private Runnable Refresh;
    
    
    public PridajReceptJDialog(Frame parent, boolean modal) {
        super(parent, modal);
        this.receptyJpanel = new ReceptyJpanel();
        //this.parent = parent;
        initComponents();
        this.getContentPane().setBackground(new Color(149,189,110));
        this.setLocationRelativeTo(parent);
        postupTextArea.setLineWrap(true);
        postupTextArea.setWrapStyleWord(true);
        ingrediencieTextArea.setLineWrap(true);
        ingrediencieTextArea.setWrapStyleWord(true);
    }
    
    public PridajReceptJDialog(Frame parent, boolean modal, Recept recept){
        super(parent, modal);
        this.receptyJpanel = new ReceptyJpanel();
        //this.parent = parent;
        initComponents();
        this.getContentPane().setBackground(new Color(149,189,110));
        this.setLocationRelativeTo(parent);
        postupTextArea.setLineWrap(true);
        postupTextArea.setWrapStyleWord(true);
        ingrediencieTextArea.setLineWrap(true);
        ingrediencieTextArea.setWrapStyleWord(true);
        
        //receptDao.pridajRecept(recept, ingrediencieTextArea.getText());
        
        nazovReceptuTextField.setText(recept.getNazov());
        postupTextArea.setText(recept.getPostup());
        ingrediencieTextArea.setText(recept.ingrediencietoString(receptDao.ingrediencieVRecepte(recept)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pridajButton = new javax.swing.JButton();
        nazovReceptuTextField = new javax.swing.JTextField();
        nazovReceptuLabel = new javax.swing.JLabel();
        ingrediencieLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingrediencieTextArea = new javax.swing.JTextArea();
        postupLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        postupTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        pridajButton.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        pridajButton.setText("Pridaj");
        pridajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajButtonActionPerformed(evt);
            }
        });

        nazovReceptuTextField.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N

        nazovReceptuLabel.setFont(new java.awt.Font("Caviar Dreams", 0, 20)); // NOI18N
        nazovReceptuLabel.setText("Pridaj názov receptu");

        ingrediencieLabel.setFont(new java.awt.Font("Caviar Dreams", 0, 20)); // NOI18N
        ingrediencieLabel.setText("Pridaj ingrediencie oddelené čiarkou");

        ingrediencieTextArea.setColumns(20);
        ingrediencieTextArea.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        ingrediencieTextArea.setRows(5);
        jScrollPane1.setViewportView(ingrediencieTextArea);

        postupLabel.setFont(new java.awt.Font("Caviar Dreams", 0, 20)); // NOI18N
        postupLabel.setText("Pridaj postup receptu");

        postupTextArea.setColumns(20);
        postupTextArea.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        postupTextArea.setRows(5);
        jScrollPane2.setViewportView(postupTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nazovReceptuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingrediencieLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(postupLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(nazovReceptuTextField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pridajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(nazovReceptuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazovReceptuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingrediencieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pridajButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajButtonActionPerformed
        recept = new Recept();
        recept.setNazov(nazovReceptuTextField.getText());
        recept.setPostup(postupTextArea.getText());
        
        receptDao.pridajRecept(recept, ingrediencieTextArea.getText());
        
        //SwingUtilities.invokeLater(Refresh);
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_pridajButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PridajReceptJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PridajReceptJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PridajReceptJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PridajReceptJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PridajReceptJDialog dialog = new PridajReceptJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ingrediencieLabel;
    private javax.swing.JTextArea ingrediencieTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nazovReceptuLabel;
    private javax.swing.JTextField nazovReceptuTextField;
    private javax.swing.JLabel postupLabel;
    private javax.swing.JTextArea postupTextArea;
    private javax.swing.JButton pridajButton;
    // End of variables declaration//GEN-END:variables
}
