/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m.l.cook;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Panel;
import javax.swing.JPanel;

/**
 *
 * @author martinapivarnikova
 */
public class ReceptJDialog extends javax.swing.JDialog {

    private Recept recept;
    ZvolenyReceptIngrediencieListModel zvolenyReceptIngrediencieListModel;
    private IngredienciaDao ingredienciaDao;
    /**
     * Creates new form ReceptJDialog
     */
    public ReceptJDialog(Recept recept, Frame parent, boolean modal) {
        super(parent, modal);
        this.getContentPane().setBackground(new Color(204, 204, 153));
        this.recept=recept;
        zvolenyReceptIngrediencieListModel = new ZvolenyReceptIngrediencieListModel();
        zvolenyReceptIngrediencieListModel.nastavIngrediencievDanomRecepte(recept);
        initComponents();
        postupTextArea.setText(recept.getPostup());
        this.setLocationRelativeTo(parent);
        postupTextArea.setWrapStyleWord(true);
        postupTextArea.setLineWrap(true);
        
    }
    
    public ReceptJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        recept = new Recept();
        zvolenyReceptIngrediencieListModel = new ZvolenyReceptIngrediencieListModel();
        zvolenyReceptIngrediencieListModel.nastavIngrediencievDanomRecepte(recept);
        
        
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ingrediencieJList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        postupTextArea = new javax.swing.JTextArea();
        closeJButton = new javax.swing.JButton();
        nazovReceptuLabel = new javax.swing.JLabel();
        ingrediencieJLabel = new javax.swing.JLabel();
        postupJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 153));

        ingrediencieJList.setModel(zvolenyReceptIngrediencieListModel);
        jScrollPane1.setViewportView(ingrediencieJList);

        postupTextArea.setEditable(false);
        postupTextArea.setColumns(20);
        postupTextArea.setRows(5);
        jScrollPane2.setViewportView(postupTextArea);

        closeJButton.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        closeJButton.setText("Zavrieť");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        nazovReceptuLabel.setFont(new java.awt.Font("Caviar Dreams", 1, 36)); // NOI18N
        nazovReceptuLabel.setText(recept.getNazov());

        ingrediencieJLabel.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        ingrediencieJLabel.setText("Ingrediencie:");

        postupJLabel.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        postupJLabel.setText("Postup receptu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addComponent(closeJButton)))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ingrediencieJLabel)
                                .addGap(66, 66, 66)
                                .addComponent(postupJLabel))
                            .addComponent(nazovReceptuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(nazovReceptuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingrediencieJLabel)
                    .addComponent(postupJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeJButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReceptJDialog dialog = new ReceptJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel ingrediencieJLabel;
    private javax.swing.JList<String> ingrediencieJList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nazovReceptuLabel;
    private javax.swing.JLabel postupJLabel;
    private javax.swing.JTextArea postupTextArea;
    // End of variables declaration//GEN-END:variables
}
