package m.l.cook;

import java.awt.Color;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;

public class ReceptyJpanel extends javax.swing.JPanel {

    private ReceptyVsetkyListModel zoznamReceptovListModel;
    private ReceptDao receptDao = ObjectFactory.INSTANCE.receptDao();
    private ReceptyVyhladaneListModel vyhladajPodlaIngrediencieListModel;

    public ReceptyJpanel() {
        zoznamReceptovListModel = new ReceptyVsetkyListModel();
        vyhladajPodlaIngrediencieListModel = new ReceptyVyhladaneListModel();
        initComponents();

        setBackground(new Color(149, 189, 110));

    }

    public void aktualizovatVyhladajPodlaIngrediencieList() {
        // ziskaj model
        ReceptyVyhladaneListModel model = (ReceptyVyhladaneListModel) vyhladaneIngrediencieJList.getModel();
        // aktualizuj ho
        model.aktualizovat();
    }

    public void aktualizovatZoznamReceptovList() {
        ReceptyVsetkyListModel model = (ReceptyVsetkyListModel) vsetkyReceptyJList.getModel();
        model.aktualizovat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vsetkyReceptyJList = new javax.swing.JList<>();
        vsetkyReceptyJLabel = new javax.swing.JLabel();
        vyhladajPodlaIngrediencieJLabel = new javax.swing.JLabel();
        vyhladajPodlaIngrediencieTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        vyhladaneIngrediencieJList = new javax.swing.JList<>();
        vyhladajButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(620, 530));
        setPreferredSize(new java.awt.Dimension(620, 530));
        setRequestFocusEnabled(false);
        setSize(new java.awt.Dimension(620, 530));

        vsetkyReceptyJList.setFont(new java.awt.Font("Caviar Dreams", 1, 12)); // NOI18N
        vsetkyReceptyJList.setModel(zoznamReceptovListModel);
        vsetkyReceptyJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickedVsetkyRecepty(evt);
            }
        });
        jScrollPane1.setViewportView(vsetkyReceptyJList);

        vsetkyReceptyJLabel.setFont(new java.awt.Font("Caviar Dreams", 0, 24)); // NOI18N
        vsetkyReceptyJLabel.setText("Zoznam všetkých receptov");

        vyhladajPodlaIngrediencieJLabel.setFont(new java.awt.Font("Caviar Dreams", 0, 24)); // NOI18N
        vyhladajPodlaIngrediencieJLabel.setText("Vyhľadaj recept podľa ingrediencií");

        vyhladajPodlaIngrediencieTextField.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N

        vyhladaneIngrediencieJList.setFont(new java.awt.Font("Caviar Dreams", 1, 12)); // NOI18N
        vyhladaneIngrediencieJList.setModel(vyhladajPodlaIngrediencieListModel);
        vyhladaneIngrediencieJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickedReceptyPodlaIngrediencii(evt);
            }
        });
        jScrollPane2.setViewportView(vyhladaneIngrediencieJList);

        vyhladajButton.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        vyhladajButton.setText("Vyhľadaj");
        vyhladajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyhladajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vyhladajPodlaIngrediencieJLabel)
                            .addComponent(vsetkyReceptyJLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vyhladajPodlaIngrediencieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vyhladajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vyhladajPodlaIngrediencieJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vyhladajButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(vyhladajPodlaIngrediencieTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vsetkyReceptyJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void mouseClickedVsetkyRecepty(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickedVsetkyRecepty
        JList theList = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            
            int index = theList.locationToIndex(evt.getPoint());
 
            Recept zvolenyRecept = zoznamReceptovListModel.getObjectAt(index);
         
            ReceptyZvolenyReceptJDialog receptJDialog = new ReceptyZvolenyReceptJDialog(zvolenyRecept, (JFrame) this.getRootPane().getParent(), true);
            receptJDialog.setVisible(true);

        }


    }//GEN-LAST:event_mouseClickedVsetkyRecepty

    private void vyhladajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyhladajButtonActionPerformed
        vyhladajPodlaIngrediencieListModel.vrateneRecepty(receptDao.vyhladajReceptyPodlaIngrediencii(vyhladajPodlaIngrediencieTextField.getText()));

        aktualizovatVyhladajPodlaIngrediencieList();   
    }//GEN-LAST:event_vyhladajButtonActionPerformed

    private void mouseClickedReceptyPodlaIngrediencii(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickedReceptyPodlaIngrediencii
        JList theList = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = theList.locationToIndex(evt.getPoint());
            String string = (String) vyhladajPodlaIngrediencieListModel.getElementAt(index);
            List<Recept> recepty = receptDao.dajRecepty();
            Recept zvolenyRecept = new Recept();
            for (Recept recept : recepty) {
                if (recept.getNazov().equals(string)) {
                    zvolenyRecept = recept;
                }
            }
            ReceptyZvolenyReceptJDialog receptJDialog = new ReceptyZvolenyReceptJDialog(zvolenyRecept, (JFrame) this.getRootPane().getParent(), true);
            receptJDialog.setVisible(true);
        }
    }//GEN-LAST:event_mouseClickedReceptyPodlaIngrediencii


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel vsetkyReceptyJLabel;
    private javax.swing.JList<String> vsetkyReceptyJList;
    private javax.swing.JButton vyhladajButton;
    private javax.swing.JLabel vyhladajPodlaIngrediencieJLabel;
    private javax.swing.JTextField vyhladajPodlaIngrediencieTextField;
    private javax.swing.JList<String> vyhladaneIngrediencieJList;
    // End of variables declaration//GEN-END:variables
}
