/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m.l.cook;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Panel;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author martinapivarnikova
 */
public class ReceptyZvolenyReceptJDialog extends javax.swing.JDialog {

    private Recept recept;
    ReceptyZvolenyReceptIngrediencieListModel zvolenyReceptIngrediencieListModel;
    private ReceptDao receptDao;
    Frame parent;

    /**
     * Creates new form ReceptJDialog
     */
    public ReceptyZvolenyReceptJDialog(Recept recept, Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        this.getContentPane().setBackground(new Color(149, 189, 110));
        receptDao = ObjectFactory.INSTANCE.receptDao();
        this.recept = recept;
        zvolenyReceptIngrediencieListModel = new ReceptyZvolenyReceptIngrediencieListModel();
        zvolenyReceptIngrediencieListModel.nastavIngrediencievDanomRecepte(recept);
        initComponents();
        postupTextArea.setText(recept.getPostup());
        this.setLocationRelativeTo(parent);
        postupTextArea.setWrapStyleWord(true);
        postupTextArea.setLineWrap(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ingrediencieJList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        postupTextArea = new javax.swing.JTextArea();
        closeJButton = new javax.swing.JButton();
        nazovReceptuLabel = new javax.swing.JLabel();
        ingrediencieJLabel = new javax.swing.JLabel();
        postupJLabel = new javax.swing.JLabel();
        upravReceptJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 153));

        ingrediencieJList.setFont(new java.awt.Font("Caviar Dreams", 1, 12)); // NOI18N
        ingrediencieJList.setModel(zvolenyReceptIngrediencieListModel);
        jScrollPane1.setViewportView(ingrediencieJList);

        postupTextArea.setEditable(false);
        postupTextArea.setColumns(20);
        postupTextArea.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        postupTextArea.setRows(5);
        jScrollPane2.setViewportView(postupTextArea);

        closeJButton.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        closeJButton.setText("Zavrieť");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        nazovReceptuLabel.setFont(new java.awt.Font("Caviar Dreams", 1, 30)); // NOI18N
        nazovReceptuLabel.setText(recept.getNazov());

        ingrediencieJLabel.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        ingrediencieJLabel.setText("Ingrediencie:");

        postupJLabel.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        postupJLabel.setText("Postup receptu:");

        upravReceptJButton.setFont(new java.awt.Font("Caviar Dreams", 1, 13)); // NOI18N
        upravReceptJButton.setText("Uprav recept");
        upravReceptJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upravReceptJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ingrediencieJLabel)
                        .addGap(66, 66, 66)
                        .addComponent(postupJLabel)
                        .addGap(0, 363, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nazovReceptuLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(upravReceptJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(nazovReceptuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingrediencieJLabel)
                    .addComponent(postupJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(closeJButton)
                            .addComponent(upravReceptJButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed

    private void upravReceptJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upravReceptJButtonActionPerformed
         this.dispose();
        PridajReceptJDialog pridajReceptJDialog = new PridajReceptJDialog(parent, true, recept);
        receptDao.zmaz(recept);
        pridajReceptJDialog.setVisible(true);

       


    }//GEN-LAST:event_upravReceptJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel ingrediencieJLabel;
    private javax.swing.JList<String> ingrediencieJList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nazovReceptuLabel;
    private javax.swing.JLabel postupJLabel;
    private javax.swing.JTextArea postupTextArea;
    private javax.swing.JButton upravReceptJButton;
    // End of variables declaration//GEN-END:variables
}
